<script>
    export default{

    }
</script>

<template>
    <main>
    <article>
    <h2>Titre 1</h2>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint vel, aspernatur, natus animi veniam accusantium deserunt asperiores aperiam commodi id laboriosam optio corrupti? Ab suscipit pariatur cupiditate, vero consequuntur magnam obcaecati necessitatibus architecto corrupti repellendus at id corporis hic voluptas explicabo sapiente eos cum ipsam accusantium minima cumque neque quod. Ad nam molestias quia sunt asperiores earum placeat adipisci iusto? Quibusdam iste nihil facere modi corrupti et delectus assumenda at.</p>
    <p>Ipsam, repellat aliquam animi ex beatae laborum iure doloribus facilis magni inventore doloremque porro iste deserunt, dolores sunt. Veniam atque, voluptatem maxime veritatis impedit quae amet dicta consectetur provident. Sed minima quisquam incidunt ducimus facilis aliquid nihil, at quidem animi voluptatem culpa praesentium tenetur, sit libero quo hic officia dolorem voluptatibus suscipit reiciendis aliquam repellendus iure odit? Sequi itaque blanditiis voluptates magni mollitia similique corrupti maiores, iure id assumenda aliquam?</p>
    <p>Nisi ad tenetur necessitatibus! Molestiae obcaecati nobis mollitia unde ipsa explicabo vitae amet officiis placeat aperiam quas dolorum aspernatur perferendis quibusdam temporibus debitis, impedit voluptatem ipsum autem quae, ab modi et assumenda similique. Non alias modi porro debitis rerum autem quod perferendis adipisci, earum expedita sapiente. Amet eaque est culpa magni debitis, architecto laudantium facilis, cumque sapiente qui officiis quia quas quasi minus ratione. Ullam perspiciatis labore ea impedit et!</p>
    <p>Reiciendis qui repudiandae eaque eveniet dicta in quo nihil deleniti vitae doloribus placeat quibusdam minima architecto enim deserunt expedita voluptatibus fugiat aspernatur, odio numquam, temporibus laudantium vel! Quo deleniti hic eligendi suscipit itaque officiis ipsa quis incidunt perspiciatis, quisquam ipsum? Tenetur, odio officiis voluptates harum officia accusamus asperiores iste eos deleniti suscipit assumenda quia, ea, praesentium similique dolorum reprehenderit consequatur tempora nostrum eligendi unde a doloremque? Cupiditate pariatur perspiciatis dolores.</p>
</article>
<article>
    <h2>Titre 2</h2>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur maxime cupiditate cumque. Voluptates assumenda aliquid harum voluptas explicabo optio! Necessitatibus tempora provident, nostrum reprehenderit odit eveniet magnam neque tenetur, distinctio nesciunt explicabo. Delectus ipsa qui reprehenderit ullam facilis commodi placeat corporis animi asperiores numquam explicabo ea nemo ut nulla aliquid, repellendus eum voluptates tenetur ipsum unde veniam nisi. Sunt praesentium sapiente asperiores eligendi quia inventore ipsum similique maxime! Nihil, consequatur.</p>
    <p>Itaque vel amet, dolore obcaecati exercitationem sapiente nulla dignissimos officia maxime nesciunt soluta. Commodi consequatur, ut alias harum vel temporibus nihil animi minus voluptate quia veritatis qui eveniet in ullam adipisci, impedit labore consequuntur, provident rerum sed! Veritatis perspiciatis saepe numquam quaerat consequatur magnam possimus a, reiciendis repellat consequuntur eius laborum repellendus quasi quibusdam? Labore incidunt, minima dolores beatae esse quasi, possimus cum quam perferendis optio voluptas repellat excepturi delectus?</p>
    <p>Blanditiis, sequi culpa maiores omnis ducimus minus! Eaque, rerum? Nobis fugit fuga iure, molestiae ipsum error temporibus voluptas repellendus delectus fugiat nostrum, deleniti quasi et eum ipsa facere modi recusandae, ex quisquam ab nam? Odit fugit unde quae animi cupiditate ratione minus voluptatum quisquam voluptate nemo eligendi delectus temporibus nisi sit totam est dolorem, recusandae repellendus corrupti sapiente itaque in neque! Cumque, minima odio recusandae omnis eaque quo dolorem enim.</p>
    <p>Ad nostrum harum aliquam quia ab in. Blanditiis dignissimos porro rem ullam obcaecati molestiae enim sunt magnam! Mollitia ipsam, omnis recusandae aliquam accusamus minima perspiciatis quidem eius maxime nulla officia quas vitae totam nam necessitatibus voluptate placeat, magnam dicta quasi exercitationem? Expedita, voluptatem aperiam. Nobis aliquid cupiditate consequuntur eligendi inventore molestiae culpa, nam atque doloribus beatae. Quis, asperiores. Enim natus, hic corporis autem alias distinctio fugiat ipsa eum blanditiis dignissimos.</p>
</article>
<article>
    <h2>Titre 3</h2>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum accusantium at ipsam exercitationem odio ut assumenda voluptas est laboriosam. Non dicta cumque fugit animi, maiores architecto doloribus blanditiis explicabo nihil reprehenderit obcaecati et maxime, ipsam placeat iste nesciunt exercitationem dolorum molestias quia? Nostrum magni non officiis itaque pariatur sit mollitia cupiditate suscipit numquam laboriosam libero repellat sapiente voluptatem, voluptatibus molestias culpa nesciunt exercitationem accusantium nobis vitae quisquam at. Praesentium, accusantium.</p>
    <p>Repellat necessitatibus tenetur quo tempora culpa quisquam tempore explicabo. Labore magnam molestiae, cumque adipisci, libero accusamus modi accusantium nobis iste, culpa necessitatibus iure corporis! Iste laborum ipsa officiis consequatur, nihil veniam? Iste necessitatibus expedita illum. Alias quis, mollitia numquam, iste doloremque assumenda magnam accusamus dolores dolorum excepturi sed quae sit error culpa facere rem sunt corrupti quam, neque fuga eveniet deleniti ratione placeat. Unde similique, quasi aliquam optio consequatur et?</p>
    <p>Molestiae id quo ducimus dolore, consequatur voluptatum! Omnis at, mollitia officiis nihil culpa velit corrupti illo officia dolorum beatae debitis earum maiores rerum pariatur quasi esse expedita! Numquam voluptatibus distinctio cupiditate sunt provident quae corporis assumenda delectus iste quisquam placeat debitis minus eos, illo aspernatur asperiores reiciendis ea esse at eum! Culpa deserunt odio ducimus fuga, vero illo asperiores reiciendis dolor adipisci earum hic esse rem officia ab molestiae. Voluptas.</p>
    <p>Vel, corporis fugiat. Tenetur maiores iusto saepe odit? Autem est accusamus quae, recusandae amet cum dignissimos minus exercitationem eveniet architecto quas inventore ipsa sapiente velit sint nisi. Atque deleniti laborum in, expedita esse incidunt repudiandae accusamus asperiores laudantium, vitae dignissimos repellat, dolore consequuntur. Eum cumque pariatur corrupti optio delectus tempora nam dolor nulla aspernatur veritatis repellat, ut quas suscipit, architecto eaque blanditiis quia distinctio repudiandae minima fugiat atque esse explicabo.</p>
</article>
</main>
</template>